baseURL = 'https://maximegosselin.com/'
languageCode = 'en-us'
title = "Maxime Gosselin"
theme = 'PaperMod'

[params]
  author = 'Maxime Gosselin'
  description = "Notes on PHP, event sourcing and software architecture by Maxime Gosselin."
  defaultTheme = 'auto'
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

[menu]
  [[menu.main]]
    name = 'Posts'
    url = '/posts/'
    weight = 1
  [[menu.main]]
    name = 'Tags'
    url = '/tags/'
    weight = 2
  [[menu.main]]
    name = 'LinkedIn'
    url = 'https://www.linkedin.com/in/maximegosselin'
    weight = 3
  [[menu.main]]
    name = 'GitHub'
    url = 'https://github.com/maximegosselin'
    weight = 4
